### ISSUE TITLE
Parameters Settings

### ISSUE THREAD

**Issue by Devyash29** [naj1024/pyspectrum#14]
What is the maximum frequency we can set?

**Comment by naj1024** [comment]
The maximum frequency you can set is dictated by the device you are using.
If you request a frequency out of the devices suported range then it is ignored.
   - The SpectrumAnalyser.log file will contain an entry for an out of range frequency request, along with allowed range.
   - maybe a better solution is to just set the max or min at that point.
         - i may add this as it seems sensible, i can see that it is a bit confusing when you input is ignored.
         
Also you can use the conversion field to allow for up/down converters, so you can have a a conversion factor that allows the UI to show the real frequency, say, an LNB received as against the L-Band the LNB is giving the SDR.

**Comment by naj1024** [comment]
Just pushed an update to flask that sets min/max on pluto and rtl sources.
