### ISSUE TITLE
Edit default spectrum!

### ISSUE THREAD

**Issue by Lucstay11** [naj1024/pyspectrum#8]
Hi, I'm trying to change the map color and the default gradient to give it, for example, the theme "fosphor" when starting the server. 
I tried to modify the **colourmaps.js,** **main.js**, **spectrum.js** but without success... What should I do?

**Comment by naj1024** [comment]
Spectrum.js under src/webUI/webroot has

// Colours
    this.colourIndex = 0;
    this.colourMap = colourMaps[this.colourIndex]; // map for spectrogram only

alternatively in colourmap.js reorder the map to give your prefered one at index zero.
var colourMaps = [binary, binary_inverse, turbo, fosphor, viridis, inferno, magma, jet];
