### ISSUE TITLE
Edit spectrum not work

### ISSUE THREAD

**Issue by Lucstay11** [naj1024/pyspectrum#9]
For some unexplained reason,
None of these changes affect the default spectrum color...
```
Spectrum.js under src/webUI/webroot has

// Colours
this.colourIndex = 0;
this.colourMap = colourMaps[this.colourIndex]; // map for spectrogram only

alternatively in colourmap.js reorder the map to give your prefered one at index zero.
var colourMaps = [binary, binary_inverse, turbo, fosphor, viridis, inferno, magma, jet];
```

And how could I do to activate by default the **grad option** at the launch of the spectrum?

**Comment by naj1024** [comment]
Think your browser cache needs a refresh.

    // Colours
    this.colourIndex = 3;
    this.spectrumGradient = true;

Above two changes worked for me.

**Comment by Lucstay11** [comment]
It work! Yes the Chrome browser cache not clearing all the time.
Thanks

**Comment by naj1024** [comment]
your welcome
